name: analysis

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2

      - name: Setting up Python 
        working-directory: ./
        run: ./Scripts/pythonSetup.
        
      - name: Run Python Analysis
        working-directory: ./
        run: ./Scripts/runAnalysis.sh